steps:

- name: 'node:alpine'
  entrypoint: 'npm'
  args: ['ci']

- name: 'node:alpine'
  entrypoint: 'npm'
  args: ['test']

- name: 'gcr.io/cloud-builders/docker'
  id: build_api
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "$BRANCH_NAME" == "master" ]]; then \
      docker build -t gcr.io/$PROJECT_ID/compliance-api:latest \
      -t gcr.io/$PROJECT_ID/compliance-api:$SHORT_SHA .;\
    else \
      exit 0;
    fi

images:
- 'gcr.io/$PROJECT_ID/compliance-api:latest'
- 'gcr.io/$PROJECT_ID/compliance-api:$SHORT_SHA'

